function [S01C1T1,S01C1T2,S01C1T3,S02C1T1,S02C1T3,S03C1T1,S03C1T2,S03C1T3,S04C1T1,S04C1T2,S04C1T3,S04C2T2,S04C2T3,S01C2T1,S01C2T2,S01C2T3,S02C2T1,S02C2T2,S02C2T3,S03C2T1,S03C2T2,S03C2T3,S04C2T1] = importTorquefile(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [S01C1T1,S01C1T2,S01C1T3,S02C1T1,S02C1T3,S03C1T1,S03C1T2,S03C1T3,S04C1T1,S04C1T2,S04C1T3,S04C2T2,S04C2T3,S01C2T1,S01C2T2,S01C2T3,S02C2T1,S02C2T2,S02C2T3,S03C2T1,S03C2T2,S03C2T3,S04C2T1]
%   = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [S01C1T1,S01C1T2,S01C1T3,S02C1T1,S02C1T3,S03C1T1,S03C1T2,S03C1T3,S04C1T1,S04C1T2,S04C1T3,S04C2T2,S04C2T3,S01C2T1,S01C2T2,S01C2T3,S02C2T1,S02C2T2,S02C2T3,S03C2T1,S03C2T2,S03C2T3,S04C2T1]
%   = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [S01C1T1,S01C1T2,S01C1T3,S02C1T1,S02C1T3,S03C1T1,S03C1T2,S03C1T3,S04C1T1,S04C1T2,S04C1T3,S04C2T2,S04C2T3,S01C2T1,S01C2T2,S01C2T3,S02C2T1,S02C2T2,S02C2T3,S03C2T1,S03C2T2,S03C2T3,S04C2T1] = importfile('Knee Torque Fast Walkng Slow Running.txt',1, 132);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2018/11/06 08:55:49

%% Initialize variables.
delimiter = '\t';
if nargin<=2
    startRow = 1;
    endRow = inf;
end

%% Read columns of data as text:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%*s%*s%*s%*s%*s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%*s%s%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric text to numbers.
% Replace non-numeric text with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = mat2cell(dataArray{col}, ones(length(dataArray{col}), 1));
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23]
    % Converts text in the input cell array to numbers. Replaced non-numeric
    % text with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1)
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData(row), regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if numbers.contains(',')
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(numbers, thousandsRegExp, 'once'))
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric text to numbers.
            if ~invalidThousandsSeparator
                numbers = textscan(char(strrep(numbers, ',', '')), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch
            raw{row, col} = rawData{row};
        end
    end
end


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Allocate imported array to column variable names
S01C1T1 = cell2mat(raw(:, 1));
S01C1T2 = cell2mat(raw(:, 2));
S01C1T3 = cell2mat(raw(:, 3));
S02C1T1 = cell2mat(raw(:, 4));
S02C1T3 = cell2mat(raw(:, 5));
S03C1T1 = cell2mat(raw(:, 6));
S03C1T2 = cell2mat(raw(:, 7));
S03C1T3 = cell2mat(raw(:, 8));
S04C1T1 = cell2mat(raw(:, 9));
S04C1T2 = cell2mat(raw(:, 10));
S04C1T3 = cell2mat(raw(:, 11));
S04C2T2 = cell2mat(raw(:, 12));
S04C2T3 = cell2mat(raw(:, 13));
S01C2T1 = cell2mat(raw(:, 14));
S01C2T2 = cell2mat(raw(:, 15));
S01C2T3 = cell2mat(raw(:, 16));
S02C2T1 = cell2mat(raw(:, 17));
S02C2T2 = cell2mat(raw(:, 18));
S02C2T3 = cell2mat(raw(:, 19));
S03C2T1 = cell2mat(raw(:, 20));
S03C2T2 = cell2mat(raw(:, 21));
S03C2T3 = cell2mat(raw(:, 22));
S04C2T1 = cell2mat(raw(:, 23));


